layout:
  qmk_keyboard: corne_rotated
  layout_name: LAYOUT_split_3x6_3_ex2
layers:
  DEF:
    - [
        { "s": "~", "t": "`" },
        Q,
        W,
        F,
        P,
        B,
        null,
        null,
        J,
        L,
        U,
        Y,
        { "s": ":", "t": ";" },
        null,
      ]
    - [
        null,
        { "t": "A", "h": "SUPER" },
        { "t": "R", "h": "ALT" },
        { "t": "S", "h": "CTRL" },
        { "t": "T", "h": "SHIFT" },
        G,
        null,
        null,
        M,
        { "t": "N", "h": "SHIFT" },
        { "t": "E", "h": "CTRL" },
        { "t": "I", "h": "ALT" },
        { "t": "O", "h": "SUPER" },
        { "s": '"', "t": "'" },
      ]
    - [
        null,
        Z,
        X,
        C,
        D,
        V,
        K,
        H,
        { "s": "<", "t": "," },
        { "s": ">", "t": "." },
        { "s": "?", "t": "/" },
        { "s": "|", t: "\\" },
      ]
    - { "t": "Esc", "h": "NAV" }
    - { "t": "Tab", "h": "NUM" }
    - { "t": "Enter", "h": "SYM" }
    - { "t": "Space", "h": "MOUSE" }
    - { "t": "Bksp", "h": "MEDIA" }
    - { "t": "Del" }
  NAV:
    - [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Undo",
        "Paste",
        "Copy",
        "Cut",
        "Redo",
        "Select all",
      ]
    - [null, SUPER, ALT, CTRL, SHIFT, null, null, null, H, J, K, L, Home, End]
    - [
        null,
        null,
        null,
        null,
        null,
        null,
        Left,
        Down,
        Up,
        Right,
        Page Down,
        Page Up,
      ]
    - "▽"
    - null
    - null
    - "Print\nScreen"
    - null
    - null
  NUM:
    - [null, null, null, null, null, null, null, null, "(", 7, 8, 9, ")", null]
    - [null, SUPER, ALT, CTRL, SHIFT, FUN, null, null, "+", 4, 5, 6, "*", null]
    - [null, null, null, null, null, null, "-", 1, 2, 3, "/", null]
    - null
    - "▽"
    - null
    - "."
    - 0
    - ","
  FUN:
    - [
        null,
        LSUPER,
        LALT,
        LCTRL,
        LSHIFT,
        null,
        null,
        null,
        F12,
        F7,
        F8,
        F9,
        null,
        null,
      ]
    - [
        null,
        null,
        null,
        null,
        null,
        "▽",
        null,
        null,
        F11,
        F4,
        F5,
        F6,
        null,
        null,
      ]
    - [null, null, null, null, null, null, F10, F1, F2, F3, null, null]
    - null
    - null
    - "▽"
    - null
    - null
    - null
  SYM:
    - [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "[",
        "&",
        "*",
        "(",
        "]",
        null,
      ]
    - [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "{",
        "$",
        "%",
        "^",
        "}",
        null,
      ]
    - [null, null, null, null, null, null, "-", "!", "@", "#", "=", null]
    - "▽"
    - "▽"
    - "▽"
    - "_"
    - ")"
    - null
  MOUSE:
    - [
        null,
        null,
        "Mouse\nWheel\nLeft",
        "Mouse\nUp",
        "Mouse\nWheel\nRight",
        "Mouse\nWheel\nUp",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ]
    - [
        null,
        null,
        "Mouse\nLeft",
        "Mouse\nDown",
        "Mouse\nRight",
        "Mouse\nWheel\nDown",
        null,
        null,
        null,
        SHIFT,
        CTRL,
        ALT,
        SUPER,
        null,
      ]
    - [null, null, null, null, null, null, null, null, null, null, null, null]
    - "Mouse\n3"
    - "Mouse\n2"
    - "Mouse\n1"
    - "▽"
    - null
    - null
  MEDIA:
    - [
        null,
        null,
        "Bright.\nDown",
        "Bright.\nUp",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ]
    - [
        null,
        "Media\nPrev",
        "Vol -",
        "Vol +",
        "Media\nNext",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ]
    - [null, null, null, null, null, null, null, null, null, null, null, null]
    - "Media\nStop"
    - "Media\nPlay"
    - Mute
    - -1
    - "▽"
    - null
